[build]
  command = "composer install && npm install && npm run build && php artisan key:generate"
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

[build.environment]
  PHP_VERSION = "8.2"
  NODE_VERSION = "18"

main

APP_NAME=Portfolio
APP_ENV=production
APP_DEBUG=false
APP_URL=https://abdullah-gurkan-levent-portfolio.netlify.app 