[build]
builder = "nixpacks"
buildCommand = "composer install && php artisan key:generate && npm install && npm run build"

[deploy]
startCommand = "php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan view:cache"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 