[build]
builder = "nixpacks"
buildCommand = """
    composer install --no-dev --optimize-autoloader &&
    cp .env.example .env &&
    php artisan key:generate --force &&
    npm ci &&
    npm run build
"""

[deploy]
startCommand = """
    php artisan config:cache &&
    php artisan route:cache &&
    php artisan view:cache &&
    php artisan migrate --force
"""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 