services:
  - type: web
    name: portfolio
    env: docker
    dockerfilePath: ./Dockerfile
    region: frankfurt
    plan: free
    branch: main
    numInstances: 1
    healthCheckPath: /health
    healthCheckTimeout: 5
    buildCommand: docker build -t portfolio .
    startCommand: docker run -p $PORT:80 portfolio
    envVars:
      - key: APP_NAME
        value: Portfolio
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        sync: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql 